[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastapi[standard]==0.115.4",
    "jinja2>=3.1.4",
    "pydantic>=2.9.2",
    "uvicorn[standard]>=0.32.0",
]

